apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec
spec:
  volumes:
    - name: pv-1
      persistentVolumeClaim:
        claimName: pv-1
  containers:
    - name: use-pv
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: pv-1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
