apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-resolver
  name: nginx-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-resolver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-resolver
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver
  labels:
    run: nginx-resolver
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-resolver
