apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-critical
  name: nginx-critical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-critical
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-critical
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      nodeSelector:
       env: prod
      restartPolicy: Always
status: {}
