apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    env: prod
spec:
  containers:
  - name: nginx1
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    env: prod
spec:
  containers:
  - name: nginx2
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    env: dev
spec:
  containers:
  - name: nginx3
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx4
  labels:
    env: dev
spec:
  containers:
  - name: nginx4
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx5
  labels:
    env: dev
spec:
  containers:
  - name: nginx5
    image: nginx
